# Generated by Django 4.2.5 on 2023-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('TE', 'Техника'), ('SC', 'Наука'), ('NA', 'Природа'), ('IN', 'Интернет'), ('OT', 'Прочее')], default='OT', max_length=2, unique=True),
        ),
    ]
